# Generated by Django 4.2.1 on 2023-05-19 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.category'),
            preserve_default=False,
        ),
    ]
