# Generated by Django 4.2.1 on 2023-06-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_compte_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
