# Generated by Django 4.2.1 on 2023-06-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_articl_alter_comment_post_delete_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articl',
            new_name='Article',
        ),
    ]
