# Generated by Django 4.2.1 on 2023-06-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_comment_delete_commentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='name',
        ),
    ]
