# Generated by Django 4.2.1 on 2023-06-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_addcommenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addcommenter',
        ),
    ]
