# Generated by Django 4.2.1 on 2023-06-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_delete_addcommenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcommentaire',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
