# Generated by Django 4.2.1 on 2023-06-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_catgholy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolyChall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image', models.FileField(upload_to='holy_challenge')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.catgholy')),
            ],
        ),
    ]
