# Generated by Django 4.2.2 on 2023-07-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_holychall'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='holy_challenge')),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.catgholy')),
            ],
        ),
        migrations.DeleteModel(
            name='HolyChall',
        ),
    ]
