# Generated by Django 4.2.1 on 2023-06-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='score',
            new_name='score_to_pass',
        ),
    ]
