# Generated by Django 4.2.1 on 2023-06-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_résultat', '0002_alter_result_quiz'),
        ('quest_app', '0002_alter_question_quiz'),
        ('app_quiz', '0003_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
